1st module finished
js-tasks-ru/jsbasic-20230116-2_kllznck pull request #2
Opened 2023-01-19 20:05 UTC by kllzn

2023-01-19 20:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-01-19 20:19 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-20 12:42 UTC, SinimaWath requested changes

2023-01-20 12:42 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  total = n;
Для создания переменной нужно использовать let/const

2023-01-20 12:42 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
`return str.toUpperCase().includes('1XBET') || str.toUpperCase().includes('XXX')`

2023-01-20 12:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-21 19:31 UTC, SinimaWath approved these changes

2023-01-21 19:32 UTC, merged