Выполненный второй модуль
js-tasks-ru/jsbasic-20230116-2_kllznck pull request #3
Opened 2023-01-23 20:23 UTC by kllzn

Напутал с названиями заданий в коммитах.
Надеюсь поможете с рефакторингом первого задания

2023-01-23 20:24 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-24 11:12 UTC, SinimaWath requested changes

2023-01-24 11:12 UTC, SinimaWath commented on 2-module/1-task/index.js
> +      !isNaN(salaries[key]) &&
Проверка isNaN - не нужна, так как isFinite(NaN) === false

2023-01-24 11:12 UTC, SinimaWath commented on 2-module/3-task/index.js
> +    calculator.a = a;
тут тоже стоит this использовать

2023-01-24 12:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-24 17:04 UTC, SinimaWath approved these changes

2023-01-24 17:04 UTC, merged